version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:3000"  # Map container's port 3000 to host's port 8081
    environment:
      - GOOGLE_CALLBACK_URL=http://localhost:8081/auth/google/callback
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    env_file:
      - .env  # Use your .env file
